export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const ADDRESS_REPOSITORY = Symbol('ADDRESS_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const TRANSACTION_MANAGER = Symbol('TRANSACTION_MANAGER');
export const ACTIVATE_ACCOUNT_USECASE = Symbol('ACTIVATE_ACCOUNT_USECASE');
export const REGISTER_ACCOUNT_USECASE = Symbol('REGISTER_ACCOUNT_USECASE');
export const FIND_ACCOUNT_BY_IDENTIFIER_USECASE = Symbol(
  'FIND_ACCOUNT_BY_IDENTIFIER_USECASE',
);
