export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const ADDRESS_REPOSITORY = Symbol('ADDRESS_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const TRANSACTION_MANAGER = Symbol('TRANSACTION_MANAGER');
export const ACTIVATE_ACCOUNT_USECASE = Symbol('ACTIVATE_ACCOUNT_USECASE');
export const REGISTER_ACCOUNT_USECASE = Symbol('REGISTER_ACCOUNT_USECASE');
export const CHANGE_ACCOUNT_PASSWORD_USECASE = Symbol(
  'CHANGE_ACCOUNT_PASSWORD_USECASE',
);
export const FIND_ACCOUNT_BY_IDENTIFIER_USECASE = Symbol(
  'FIND_ACCOUNT_BY_IDENTIFIER_USECASE',
);
export const CHANGE_OWN_PASSWORD_USECASE = Symbol(
  'CHANGE_OWN_PASSWORD_USECASE',
);
export const UPDATE_ACCOUNT_PROFILE_USECASE = Symbol(
  'UPDATE_ACCOUNT_PROFILE_USECASE',
);
export const GET_ACCOUNT_ADDRESSES_USECASE = Symbol(
  'GET_ACCOUNT_ADDRESSES_USECASE',
);
export const SET_CURRENT_ADDRESS_USECASE = Symbol(
  'SET_CURRENT_ADDRESS_USECASE',
);
export const CREATE_ADDRESS_USECASE = Symbol('CREATE_ADDRESS_USECASE');
export const DELETE_ADDRESS_USECASE = Symbol('DELETE_ADDRESS_USECASE');
export const FIND_ACCOUNT_BY_ID_USECASE = Symbol('FIND_ACCOUNT_BY_ID_USECASE');
export const CREATE_PROFILE_USECASE = Symbol('CREATE_PROFILE_USECASE');
