export const COMMENT_REPOSITORY = Symbol('COMMENT_REPOSITORY');
export const CREATE_COMMENT_USECASE = Symbol('CREATE_COMMENT_USECASE');
export const DELETE_COMMENT_USECASE = Symbol('DELETE_COMMENT_USECASE');
export const GET_COMMENTS_USECASE = Symbol('GET_COMMENTS_USECASE');
