export const OTP_REPOSITORY = Symbol('OTP_REPOSITORY');
export const OTP_SENDER = Symbol('OTP_SENDER');
export const VERIFY_OTP_USECASE = Symbol('VERIFY_OTP_USECASE');
export const ISSUE_ACCOUNT_VERIFICATION_USECASE = Symbol(
  'ISSUE_ACCOUNT_VERIFICATION_USECASE',
);
export const ISSUE_RESET_PASSWORD_OTP_USECASE = Symbol(
  'ISSUE_RESET_PASSWORD_OTP_USECASE',
);
