export const CHAT_REPOSITORY = Symbol('CHAT_REPOSITORY');
export const SEND_CHAT_MESSAGE_USECASE = Symbol('SEND_CHAT_MESSAGE_USECASE');
export const GET_CHAT_ROOMS_USECASE = Symbol('GET_CHAT_ROOMS_USECASE');
export const GET_CHAT_MESSAGES_USECASE = Symbol('GET_CHAT_MESSAGES_USECASE');
