export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const NOTIFICATION_REALTIME_PORT = Symbol('NOTIFICATION_REALTIME_PORT');
export const CREATE_NOTIFICATION_USECASE = Symbol(
  'CREATE_NOTIFICATION_USECASE',
);
export const GET_NOTIFICATIONS_USECASE = Symbol('GET_NOTIFICATIONS_USECASE');
export const GET_UNREAD_NOTIFICATION_COUNT_USECASE = Symbol(
  'GET_UNREAD_NOTIFICATION_COUNT_USECASE',
);
export const MARK_NOTIFICATION_AS_READ_USECASE = Symbol(
  'MARK_NOTIFICATION_AS_READ_USECASE',
);
export const MARK_ALL_NOTIFICATIONS_AS_READ_USECASE = Symbol(
  'MARK_ALL_NOTIFICATIONS_AS_READ_USECASE',
);
