export const POST_REPOSITORY = Symbol('POST_REPOSITORY');
export const CREATE_POST_USECASE = Symbol('CREATE_POST_USECASE');
export const FIND_POST_BY_ID_USECASE = Symbol('FIND_POST_BY_ID_USECASE');
export const INCREMENT_POST_LIKE_COUNT_USECASE = Symbol(
  'INCREMENT_POST_LIKE_COUNT_USECASE',
);
export const DECREMENT_POST_LIKE_COUNT_USECASE = Symbol(
  'DECREMENT_POST_LIKE_COUNT_USECASE',
);
